-- Generated by @kiwa-lab/lean — do not edit by hand.
-- Spec: CacheLifecycleOrchestrator (5 states × 8 events = 40 cells)
-- Valid transitions: 15  Rejected: 25
--
-- Every cell is listed and there is no catch-all, so Lean's exhaustiveness
-- checker is what proves the table is complete. Removing a line is a compile
-- error naming the cell, not a silent fallthrough.

namespace «Cache»

inductive State where
  | Filling : State
  | Hot : State
  | Expiring : State
  | Stale : State
  | Evicted : State
deriving DecidableEq, Repr

inductive Event where
  | WriteCommitted : Event
  | ReadHit : Event
  | ReadMiss : Event
  | TtlWarning : Event
  | TtlExpired : Event
  | InvalidateRequested : Event
  | EvictRequested : Event
  | Timeout : Event
deriving DecidableEq, Repr

/-- The result of feeding an event to a state: either a next state, or a
rejection. A self-loop steps back to the same state, which is a decision, and is
therefore distinguishable from a rejection. -/
inductive Step where
  | to : State → Step
  | invalid : Step
deriving DecidableEq, Repr

def dispatch : State → Event → Step
  | .Filling,  .WriteCommitted      => .to .Hot
  | .Filling,  .ReadHit             => .invalid
  | .Filling,  .ReadMiss            => .invalid
  | .Filling,  .TtlWarning          => .invalid
  | .Filling,  .TtlExpired          => .invalid
  | .Filling,  .InvalidateRequested => .invalid
  | .Filling,  .EvictRequested      => .invalid
  | .Filling,  .Timeout             => .to .Evicted
  | .Hot,      .WriteCommitted      => .to .Hot
  | .Hot,      .ReadHit             => .to .Hot
  | .Hot,      .ReadMiss            => .invalid
  | .Hot,      .TtlWarning          => .to .Expiring
  | .Hot,      .TtlExpired          => .invalid
  | .Hot,      .InvalidateRequested => .to .Evicted
  | .Hot,      .EvictRequested      => .invalid
  | .Hot,      .Timeout             => .to .Evicted
  | .Expiring, .WriteCommitted      => .invalid
  | .Expiring, .ReadHit             => .to .Expiring
  | .Expiring, .ReadMiss            => .invalid
  | .Expiring, .TtlWarning          => .invalid
  | .Expiring, .TtlExpired          => .to .Stale
  | .Expiring, .InvalidateRequested => .invalid
  | .Expiring, .EvictRequested      => .to .Evicted
  | .Expiring, .Timeout             => .to .Evicted
  | .Stale,    .WriteCommitted      => .to .Filling
  | .Stale,    .ReadHit             => .invalid
  | .Stale,    .ReadMiss            => .to .Stale
  | .Stale,    .TtlWarning          => .invalid
  | .Stale,    .TtlExpired          => .invalid
  | .Stale,    .InvalidateRequested => .invalid
  | .Stale,    .EvictRequested      => .to .Evicted
  | .Stale,    .Timeout             => .to .Evicted
  | .Evicted,  .WriteCommitted      => .invalid
  | .Evicted,  .ReadHit             => .invalid
  | .Evicted,  .ReadMiss            => .invalid
  | .Evicted,  .TtlWarning          => .invalid
  | .Evicted,  .TtlExpired          => .invalid
  | .Evicted,  .InvalidateRequested => .invalid
  | .Evicted,  .EvictRequested      => .invalid
  | .Evicted,  .Timeout             => .invalid

/-- Whether an event moves the machine to a different state. A self-loop does
not: it is accepted, and it goes nowhere. -/
def escapes (s : State) (e : Event) : Bool :=
  match dispatch s e with
  | .to s' => !(decide (s' = s))
  | .invalid => false

/-- Feed a sequence of events, stopping at the first rejection. -/
def steps : State → List Event → Step
  | s, [] => .to s
  | s, e :: rest =>
    match dispatch s e with
    | .to s' => steps s' rest
    | .invalid => .invalid

/-- State evicted is terminal: no event leads anywhere from it. -/
theorem evicted_absorbing : ∀ e, dispatch .Evicted e = .invalid := by
  intro e; cases e <;> rfl

/-- State filling can leave, and this event does it. -/
theorem filling_can_leave : ∃ e, escapes .Filling e = true :=
  ⟨.WriteCommitted, rfl⟩

/-- State hot can leave, and this event does it. -/
theorem hot_can_leave : ∃ e, escapes .Hot e = true :=
  ⟨.TtlWarning, rfl⟩

/-- State expiring can leave, and this event does it. -/
theorem expiring_can_leave : ∃ e, escapes .Expiring e = true :=
  ⟨.TtlExpired, rfl⟩

/-- State stale can leave, and this event does it. -/
theorem stale_can_leave : ∃ e, escapes .Stale e = true :=
  ⟨.WriteCommitted, rfl⟩

/-- State hot is reachable from filling. -/
theorem hot_reachable : steps .Filling [.WriteCommitted] = .to .Hot := rfl

/-- State evicted is reachable from filling. -/
theorem evicted_reachable : steps .Filling [.Timeout] = .to .Evicted := rfl

/-- State expiring is reachable from filling. -/
theorem expiring_reachable : steps .Filling [.WriteCommitted, .TtlWarning] = .to .Expiring := rfl

/-- State stale is reachable from filling. -/
theorem stale_reachable : steps .Filling [.WriteCommitted, .TtlWarning, .TtlExpired] = .to .Stale := rfl

end «Cache»
