-- Generated by @kiwa-lab/lean — do not edit by hand.
-- Spec: CliLifecycleOrchestrator (5 states × 8 events = 40 cells)
-- Valid transitions: 12  Rejected: 28
--
-- Every cell is listed and there is no catch-all, so Lean's exhaustiveness
-- checker is what proves the table is complete. Removing a line is a compile
-- error naming the cell, not a silent fallthrough.

namespace «Cli»

inductive State where
  | Spawning : State
  | Running : State
  | Signaled : State
  | Exited : State
  | Cleaned : State
deriving DecidableEq, Repr

inductive Event where
  | SpawnSucceeded : Event
  | StdoutReceived : Event
  | StderrReceived : Event
  | SignalSent : Event
  | ExitDetected : Event
  | CleanupRequested : Event
  | ZombieDetected : Event
  | Timeout : Event
deriving DecidableEq, Repr

/-- The result of feeding an event to a state: either a next state, or a
rejection. A self-loop steps back to the same state, which is a decision, and is
therefore distinguishable from a rejection. -/
inductive Step where
  | to : State → Step
  | invalid : Step
deriving DecidableEq, Repr

def dispatch : State → Event → Step
  | .Spawning, .SpawnSucceeded   => .to .Running
  | .Spawning, .StdoutReceived   => .invalid
  | .Spawning, .StderrReceived   => .invalid
  | .Spawning, .SignalSent       => .invalid
  | .Spawning, .ExitDetected     => .invalid
  | .Spawning, .CleanupRequested => .invalid
  | .Spawning, .ZombieDetected   => .invalid
  | .Spawning, .Timeout          => .to .Exited
  | .Running,  .SpawnSucceeded   => .invalid
  | .Running,  .StdoutReceived   => .to .Running
  | .Running,  .StderrReceived   => .to .Running
  | .Running,  .SignalSent       => .to .Signaled
  | .Running,  .ExitDetected     => .to .Exited
  | .Running,  .CleanupRequested => .invalid
  | .Running,  .ZombieDetected   => .invalid
  | .Running,  .Timeout          => .to .Exited
  | .Signaled, .SpawnSucceeded   => .invalid
  | .Signaled, .StdoutReceived   => .invalid
  | .Signaled, .StderrReceived   => .invalid
  | .Signaled, .SignalSent       => .invalid
  | .Signaled, .ExitDetected     => .to .Exited
  | .Signaled, .CleanupRequested => .invalid
  | .Signaled, .ZombieDetected   => .to .Signaled
  | .Signaled, .Timeout          => .to .Exited
  | .Exited,   .SpawnSucceeded   => .invalid
  | .Exited,   .StdoutReceived   => .invalid
  | .Exited,   .StderrReceived   => .invalid
  | .Exited,   .SignalSent       => .invalid
  | .Exited,   .ExitDetected     => .invalid
  | .Exited,   .CleanupRequested => .to .Cleaned
  | .Exited,   .ZombieDetected   => .to .Exited
  | .Exited,   .Timeout          => .invalid
  | .Cleaned,  .SpawnSucceeded   => .invalid
  | .Cleaned,  .StdoutReceived   => .invalid
  | .Cleaned,  .StderrReceived   => .invalid
  | .Cleaned,  .SignalSent       => .invalid
  | .Cleaned,  .ExitDetected     => .invalid
  | .Cleaned,  .CleanupRequested => .invalid
  | .Cleaned,  .ZombieDetected   => .invalid
  | .Cleaned,  .Timeout          => .invalid

/-- Whether an event moves the machine to a different state. A self-loop does
not: it is accepted, and it goes nowhere. -/
def escapes (s : State) (e : Event) : Bool :=
  match dispatch s e with
  | .to s' => !(decide (s' = s))
  | .invalid => false

/-- Feed a sequence of events, stopping at the first rejection. -/
def steps : State → List Event → Step
  | s, [] => .to s
  | s, e :: rest =>
    match dispatch s e with
    | .to s' => steps s' rest
    | .invalid => .invalid

/-- State cleaned is terminal: no event leads anywhere from it. -/
theorem cleaned_absorbing : ∀ e, dispatch .Cleaned e = .invalid := by
  intro e; cases e <;> rfl

/-- State spawning can leave, and this event does it. -/
theorem spawning_can_leave : ∃ e, escapes .Spawning e = true :=
  ⟨.SpawnSucceeded, rfl⟩

/-- State running can leave, and this event does it. -/
theorem running_can_leave : ∃ e, escapes .Running e = true :=
  ⟨.SignalSent, rfl⟩

/-- State signaled can leave, and this event does it. -/
theorem signaled_can_leave : ∃ e, escapes .Signaled e = true :=
  ⟨.ExitDetected, rfl⟩

/-- State exited can leave, and this event does it. -/
theorem exited_can_leave : ∃ e, escapes .Exited e = true :=
  ⟨.CleanupRequested, rfl⟩

/-- State running is reachable from spawning. -/
theorem running_reachable : steps .Spawning [.SpawnSucceeded] = .to .Running := rfl

/-- State exited is reachable from spawning. -/
theorem exited_reachable : steps .Spawning [.Timeout] = .to .Exited := rfl

/-- State signaled is reachable from spawning. -/
theorem signaled_reachable : steps .Spawning [.SpawnSucceeded, .SignalSent] = .to .Signaled := rfl

/-- State cleaned is reachable from spawning. -/
theorem cleaned_reachable : steps .Spawning [.Timeout, .CleanupRequested] = .to .Cleaned := rfl

end «Cli»
