-- Generated by @kiwa-lab/lean — do not edit by hand.
-- Spec: JobLifecycleOrchestrator (5 states × 8 events = 40 cells)
-- Valid transitions: 10  Rejected: 30
--
-- Every cell is listed and there is no catch-all, so Lean's exhaustiveness
-- checker is what proves the table is complete. Removing a line is a compile
-- error naming the cell, not a silent fallthrough.

namespace «Job»

inductive State where
  | Queued : State
  | Processing : State
  | Retrying : State
  | Dlq : State
  | Completed : State
deriving DecidableEq, Repr

inductive Event where
  | EnqueueSucceeded : Event
  | ProcessStarted : Event
  | ProcessSucceeded : Event
  | ProcessFailed : Event
  | RetryScheduled : Event
  | RetryExhausted : Event
  | DlqInspected : Event
  | Timeout : Event
deriving DecidableEq, Repr

/-- The result of feeding an event to a state: either a next state, or a
rejection. A self-loop steps back to the same state, which is a decision, and is
therefore distinguishable from a rejection. -/
inductive Step where
  | to : State → Step
  | invalid : Step
deriving DecidableEq, Repr

def dispatch : State → Event → Step
  | .Queued,     .EnqueueSucceeded => .to .Queued
  | .Queued,     .ProcessStarted   => .to .Processing
  | .Queued,     .ProcessSucceeded => .invalid
  | .Queued,     .ProcessFailed    => .invalid
  | .Queued,     .RetryScheduled   => .invalid
  | .Queued,     .RetryExhausted   => .invalid
  | .Queued,     .DlqInspected     => .invalid
  | .Queued,     .Timeout          => .to .Dlq
  | .Processing, .EnqueueSucceeded => .invalid
  | .Processing, .ProcessStarted   => .invalid
  | .Processing, .ProcessSucceeded => .to .Completed
  | .Processing, .ProcessFailed    => .to .Retrying
  | .Processing, .RetryScheduled   => .invalid
  | .Processing, .RetryExhausted   => .invalid
  | .Processing, .DlqInspected     => .invalid
  | .Processing, .Timeout          => .to .Dlq
  | .Retrying,   .EnqueueSucceeded => .invalid
  | .Retrying,   .ProcessStarted   => .invalid
  | .Retrying,   .ProcessSucceeded => .invalid
  | .Retrying,   .ProcessFailed    => .invalid
  | .Retrying,   .RetryScheduled   => .to .Queued
  | .Retrying,   .RetryExhausted   => .to .Dlq
  | .Retrying,   .DlqInspected     => .invalid
  | .Retrying,   .Timeout          => .to .Dlq
  | .Dlq,        .EnqueueSucceeded => .invalid
  | .Dlq,        .ProcessStarted   => .invalid
  | .Dlq,        .ProcessSucceeded => .invalid
  | .Dlq,        .ProcessFailed    => .invalid
  | .Dlq,        .RetryScheduled   => .invalid
  | .Dlq,        .RetryExhausted   => .invalid
  | .Dlq,        .DlqInspected     => .to .Dlq
  | .Dlq,        .Timeout          => .invalid
  | .Completed,  .EnqueueSucceeded => .invalid
  | .Completed,  .ProcessStarted   => .invalid
  | .Completed,  .ProcessSucceeded => .invalid
  | .Completed,  .ProcessFailed    => .invalid
  | .Completed,  .RetryScheduled   => .invalid
  | .Completed,  .RetryExhausted   => .invalid
  | .Completed,  .DlqInspected     => .invalid
  | .Completed,  .Timeout          => .invalid

/-- Whether an event moves the machine to a different state. A self-loop does
not: it is accepted, and it goes nowhere. -/
def escapes (s : State) (e : Event) : Bool :=
  match dispatch s e with
  | .to s' => !(decide (s' = s))
  | .invalid => false

/-- Feed a sequence of events, stopping at the first rejection. -/
def steps : State → List Event → Step
  | s, [] => .to s
  | s, e :: rest =>
    match dispatch s e with
    | .to s' => steps s' rest
    | .invalid => .invalid

/-- State completed is terminal: no event leads anywhere from it. -/
theorem completed_absorbing : ∀ e, dispatch .Completed e = .invalid := by
  intro e; cases e <;> rfl

/-- State queued can leave, and this event does it. -/
theorem queued_can_leave : ∃ e, escapes .Queued e = true :=
  ⟨.ProcessStarted, rfl⟩

/-- State processing can leave, and this event does it. -/
theorem processing_can_leave : ∃ e, escapes .Processing e = true :=
  ⟨.ProcessSucceeded, rfl⟩

/-- State retrying can leave, and this event does it. -/
theorem retrying_can_leave : ∃ e, escapes .Retrying e = true :=
  ⟨.RetryScheduled, rfl⟩

/-- State dlq accepts events but no event leaves it: a sink. -/
theorem dlq_no_escape : ∀ e, escapes .Dlq e = false := by
  intro e; cases e <;> rfl

/-- State processing is reachable from queued. -/
theorem processing_reachable : steps .Queued [.ProcessStarted] = .to .Processing := rfl

/-- State dlq is reachable from queued. -/
theorem dlq_reachable : steps .Queued [.Timeout] = .to .Dlq := rfl

/-- State completed is reachable from queued. -/
theorem completed_reachable : steps .Queued [.ProcessStarted, .ProcessSucceeded] = .to .Completed := rfl

/-- State retrying is reachable from queued. -/
theorem retrying_reachable : steps .Queued [.ProcessStarted, .ProcessFailed] = .to .Retrying := rfl

end «Job»
