-- Generated by @kiwa-lab/lean — do not edit by hand.
-- Spec: SessionLifecycleOrchestrator (5 states × 8 events = 40 cells)
-- Valid transitions: 12  Rejected: 28
--
-- Every cell is listed and there is no catch-all, so Lean's exhaustiveness
-- checker is what proves the table is complete. Removing a line is a compile
-- error naming the cell, not a silent fallthrough.

namespace «Session»

inductive State where
  | Init : State
  | Authed : State
  | Refreshing : State
  | Expired : State
  | Revoked : State
deriving DecidableEq, Repr

inductive Event where
  | AuthSucceeded : Event
  | AuthFailed : Event
  | RefreshTriggered : Event
  | RefreshSucceeded : Event
  | RefreshFailed : Event
  | SessionExpired : Event
  | RevokeRequested : Event
  | Timeout : Event
deriving DecidableEq, Repr

/-- The result of feeding an event to a state: either a next state, or a
rejection. A self-loop steps back to the same state, which is a decision, and is
therefore distinguishable from a rejection. -/
inductive Step where
  | to : State → Step
  | invalid : Step
deriving DecidableEq, Repr

def dispatch : State → Event → Step
  | .Init,       .AuthSucceeded    => .to .Authed
  | .Init,       .AuthFailed       => .to .Init
  | .Init,       .RefreshTriggered => .invalid
  | .Init,       .RefreshSucceeded => .invalid
  | .Init,       .RefreshFailed    => .invalid
  | .Init,       .SessionExpired   => .invalid
  | .Init,       .RevokeRequested  => .invalid
  | .Init,       .Timeout          => .to .Expired
  | .Authed,     .AuthSucceeded    => .invalid
  | .Authed,     .AuthFailed       => .invalid
  | .Authed,     .RefreshTriggered => .to .Refreshing
  | .Authed,     .RefreshSucceeded => .invalid
  | .Authed,     .RefreshFailed    => .invalid
  | .Authed,     .SessionExpired   => .to .Expired
  | .Authed,     .RevokeRequested  => .to .Revoked
  | .Authed,     .Timeout          => .to .Expired
  | .Refreshing, .AuthSucceeded    => .invalid
  | .Refreshing, .AuthFailed       => .invalid
  | .Refreshing, .RefreshTriggered => .invalid
  | .Refreshing, .RefreshSucceeded => .to .Authed
  | .Refreshing, .RefreshFailed    => .to .Expired
  | .Refreshing, .SessionExpired   => .invalid
  | .Refreshing, .RevokeRequested  => .to .Revoked
  | .Refreshing, .Timeout          => .to .Expired
  | .Expired,    .AuthSucceeded    => .invalid
  | .Expired,    .AuthFailed       => .invalid
  | .Expired,    .RefreshTriggered => .invalid
  | .Expired,    .RefreshSucceeded => .invalid
  | .Expired,    .RefreshFailed    => .invalid
  | .Expired,    .SessionExpired   => .invalid
  | .Expired,    .RevokeRequested  => .to .Revoked
  | .Expired,    .Timeout          => .invalid
  | .Revoked,    .AuthSucceeded    => .invalid
  | .Revoked,    .AuthFailed       => .invalid
  | .Revoked,    .RefreshTriggered => .invalid
  | .Revoked,    .RefreshSucceeded => .invalid
  | .Revoked,    .RefreshFailed    => .invalid
  | .Revoked,    .SessionExpired   => .invalid
  | .Revoked,    .RevokeRequested  => .invalid
  | .Revoked,    .Timeout          => .invalid

/-- Whether an event moves the machine to a different state. A self-loop does
not: it is accepted, and it goes nowhere. -/
def escapes (s : State) (e : Event) : Bool :=
  match dispatch s e with
  | .to s' => !(decide (s' = s))
  | .invalid => false

/-- Feed a sequence of events, stopping at the first rejection. -/
def steps : State → List Event → Step
  | s, [] => .to s
  | s, e :: rest =>
    match dispatch s e with
    | .to s' => steps s' rest
    | .invalid => .invalid

/-- State revoked is terminal: no event leads anywhere from it. -/
theorem revoked_absorbing : ∀ e, dispatch .Revoked e = .invalid := by
  intro e; cases e <;> rfl

/-- State init can leave, and this event does it. -/
theorem init_can_leave : ∃ e, escapes .Init e = true :=
  ⟨.AuthSucceeded, rfl⟩

/-- State authed can leave, and this event does it. -/
theorem authed_can_leave : ∃ e, escapes .Authed e = true :=
  ⟨.RefreshTriggered, rfl⟩

/-- State refreshing can leave, and this event does it. -/
theorem refreshing_can_leave : ∃ e, escapes .Refreshing e = true :=
  ⟨.RefreshSucceeded, rfl⟩

/-- State expired can leave, and this event does it. -/
theorem expired_can_leave : ∃ e, escapes .Expired e = true :=
  ⟨.RevokeRequested, rfl⟩

/-- State authed is reachable from init. -/
theorem authed_reachable : steps .Init [.AuthSucceeded] = .to .Authed := rfl

/-- State expired is reachable from init. -/
theorem expired_reachable : steps .Init [.Timeout] = .to .Expired := rfl

/-- State refreshing is reachable from init. -/
theorem refreshing_reachable : steps .Init [.AuthSucceeded, .RefreshTriggered] = .to .Refreshing := rfl

/-- State revoked is reachable from init. -/
theorem revoked_reachable : steps .Init [.AuthSucceeded, .RevokeRequested] = .to .Revoked := rfl

end «Session»
