-- Generated by @kiwa-lab/lean — do not edit by hand.
-- Spec: TransactionOrchestrator (5 states × 8 events = 40 cells)
-- Valid transitions: 14  Rejected: 26
--
-- Every cell is listed and there is no catch-all, so Lean's exhaustiveness
-- checker is what proves the table is complete. Removing a line is a compile
-- error naming the cell, not a silent fallthrough.

namespace «Transaction»

inductive State where
  | Beginning : State
  | Active : State
  | SavepointNested : State
  | Committing : State
  | Aborted : State
deriving DecidableEq, Repr

inductive Event where
  | BeginCompleted : Event
  | QueryExecuted : Event
  | SavepointCreated : Event
  | SavepointReleased : Event
  | CommitRequested : Event
  | CommitSucceeded : Event
  | RollbackRequested : Event
  | Timeout : Event
deriving DecidableEq, Repr

/-- The result of feeding an event to a state: either a next state, or a
rejection. A self-loop steps back to the same state, which is a decision, and is
therefore distinguishable from a rejection. -/
inductive Step where
  | to : State → Step
  | invalid : Step
deriving DecidableEq, Repr

def dispatch : State → Event → Step
  | .Beginning,       .BeginCompleted    => .to .Active
  | .Beginning,       .QueryExecuted     => .invalid
  | .Beginning,       .SavepointCreated  => .invalid
  | .Beginning,       .SavepointReleased => .invalid
  | .Beginning,       .CommitRequested   => .invalid
  | .Beginning,       .CommitSucceeded   => .invalid
  | .Beginning,       .RollbackRequested => .to .Aborted
  | .Beginning,       .Timeout           => .to .Aborted
  | .Active,          .BeginCompleted    => .invalid
  | .Active,          .QueryExecuted     => .to .Active
  | .Active,          .SavepointCreated  => .to .SavepointNested
  | .Active,          .SavepointReleased => .invalid
  | .Active,          .CommitRequested   => .to .Committing
  | .Active,          .CommitSucceeded   => .invalid
  | .Active,          .RollbackRequested => .to .Aborted
  | .Active,          .Timeout           => .to .Aborted
  | .SavepointNested, .BeginCompleted    => .invalid
  | .SavepointNested, .QueryExecuted     => .to .SavepointNested
  | .SavepointNested, .SavepointCreated  => .invalid
  | .SavepointNested, .SavepointReleased => .to .Active
  | .SavepointNested, .CommitRequested   => .invalid
  | .SavepointNested, .CommitSucceeded   => .invalid
  | .SavepointNested, .RollbackRequested => .to .Aborted
  | .SavepointNested, .Timeout           => .to .Aborted
  | .Committing,      .BeginCompleted    => .invalid
  | .Committing,      .QueryExecuted     => .invalid
  | .Committing,      .SavepointCreated  => .invalid
  | .Committing,      .SavepointReleased => .invalid
  | .Committing,      .CommitRequested   => .invalid
  | .Committing,      .CommitSucceeded   => .to .Committing
  | .Committing,      .RollbackRequested => .invalid
  | .Committing,      .Timeout           => .to .Aborted
  | .Aborted,         .BeginCompleted    => .invalid
  | .Aborted,         .QueryExecuted     => .invalid
  | .Aborted,         .SavepointCreated  => .invalid
  | .Aborted,         .SavepointReleased => .invalid
  | .Aborted,         .CommitRequested   => .invalid
  | .Aborted,         .CommitSucceeded   => .invalid
  | .Aborted,         .RollbackRequested => .invalid
  | .Aborted,         .Timeout           => .invalid

/-- Whether an event moves the machine to a different state. A self-loop does
not: it is accepted, and it goes nowhere. -/
def escapes (s : State) (e : Event) : Bool :=
  match dispatch s e with
  | .to s' => !(decide (s' = s))
  | .invalid => false

/-- Feed a sequence of events, stopping at the first rejection. -/
def steps : State → List Event → Step
  | s, [] => .to s
  | s, e :: rest =>
    match dispatch s e with
    | .to s' => steps s' rest
    | .invalid => .invalid

/-- State aborted is terminal: no event leads anywhere from it. -/
theorem aborted_absorbing : ∀ e, dispatch .Aborted e = .invalid := by
  intro e; cases e <;> rfl

/-- State beginning can leave, and this event does it. -/
theorem beginning_can_leave : ∃ e, escapes .Beginning e = true :=
  ⟨.BeginCompleted, rfl⟩

/-- State active can leave, and this event does it. -/
theorem active_can_leave : ∃ e, escapes .Active e = true :=
  ⟨.SavepointCreated, rfl⟩

/-- State savepoint-nested can leave, and this event does it. -/
theorem savepoint_nested_can_leave : ∃ e, escapes .SavepointNested e = true :=
  ⟨.SavepointReleased, rfl⟩

/-- State committing can leave, and this event does it. -/
theorem committing_can_leave : ∃ e, escapes .Committing e = true :=
  ⟨.Timeout, rfl⟩

/-- State active is reachable from beginning. -/
theorem active_reachable : steps .Beginning [.BeginCompleted] = .to .Active := rfl

/-- State aborted is reachable from beginning. -/
theorem aborted_reachable : steps .Beginning [.RollbackRequested] = .to .Aborted := rfl

/-- State savepoint-nested is reachable from beginning. -/
theorem savepoint_nested_reachable : steps .Beginning [.BeginCompleted, .SavepointCreated] = .to .SavepointNested := rfl

/-- State committing is reachable from beginning. -/
theorem committing_reachable : steps .Beginning [.BeginCompleted, .CommitRequested] = .to .Committing := rfl

end «Transaction»
