"""HTTP adapters that wrap requests / httpx for kiwa pytest fixtures.

Both adapters expose a single `.request(method, url, **kwargs)` entry plus
shorthand helpers (`get`, `post`, `put`, `delete`, `patch`). They are designed
so test bodies generated by `/kiwa-design --layer api` can drop straight in.
"""

from __future__ import annotations

from typing import Any, Dict, Optional

try:
    import requests as _requests_module  # type: ignore[import-untyped]
except ImportError:  # pragma: no cover
    _requests_module = None

try:
    import httpx as _httpx_module
except ImportError:  # pragma: no cover
    _httpx_module = None


class _BaseAdapter:
    def __init__(self, base_url: str = ""):
        self.base_url = base_url.rstrip("/")

    def _resolve(self, path: str) -> str:
        if path.startswith("http://") or path.startswith("https://"):
            return path
        if not path.startswith("/"):
            path = "/" + path
        return f"{self.base_url}{path}"

    def get(self, path: str, **kwargs: Any) -> Any:
        return self.request("GET", path, **kwargs)

    def post(self, path: str, **kwargs: Any) -> Any:
        return self.request("POST", path, **kwargs)

    def put(self, path: str, **kwargs: Any) -> Any:
        return self.request("PUT", path, **kwargs)

    def delete(self, path: str, **kwargs: Any) -> Any:
        return self.request("DELETE", path, **kwargs)

    def patch(self, path: str, **kwargs: Any) -> Any:
        return self.request("PATCH", path, **kwargs)

    def request(self, method: str, path: str, **kwargs: Any) -> Any:  # pragma: no cover - abstract
        raise NotImplementedError


class RequestsAdapter(_BaseAdapter):
    """Synchronous adapter using `requests`."""

    def __init__(self, base_url: str = "", session: Optional[Any] = None):
        super().__init__(base_url)
        if _requests_module is None:
            raise RuntimeError(
                "kiwa-test-py: `requests` is not installed; install with `pip install kiwa-test-py[requests]`"
            )
        self._session = session or _requests_module.Session()

    def request(self, method: str, path: str, **kwargs: Any) -> Any:
        url = self._resolve(path)
        return self._session.request(method, url, **kwargs)

    def close(self) -> None:
        self._session.close()


class HttpxAdapter(_BaseAdapter):
    """Adapter using `httpx.Client` (sync) or `httpx.AsyncClient` (async)."""

    def __init__(self, base_url: str = "", client: Optional[Any] = None, async_client: bool = False):
        super().__init__(base_url)
        if _httpx_module is None:
            raise RuntimeError(
                "kiwa-test-py: `httpx` is not installed; install with `pip install kiwa-test-py[httpx]`"
            )
        if client is not None:
            self._client = client
        elif async_client:
            self._client = _httpx_module.AsyncClient()
        else:
            self._client = _httpx_module.Client()

    def request(self, method: str, path: str, **kwargs: Any) -> Any:
        url = self._resolve(path)
        return self._client.request(method, url, **kwargs)

    def close(self) -> None:
        if hasattr(self._client, "close"):
            self._client.close()


def requests_adapter(base_url: str = "", **kwargs: Dict[str, Any]) -> RequestsAdapter:
    """Factory: returns a sync RequestsAdapter."""
    return RequestsAdapter(base_url=base_url, **kwargs)


def httpx_adapter(base_url: str = "", **kwargs: Dict[str, Any]) -> HttpxAdapter:
    """Factory: returns an HttpxAdapter (sync by default, pass async_client=True for async)."""
    return HttpxAdapter(base_url=base_url, **kwargs)
