type Locale = "en" | "ja";

export const tokens = {
  locale: "ja" as Locale,
  color: {
    bg: "#0F1419",
    bgGradientEnd: "#1A1F2E",
    primary: "#7CB342",
    primaryDark: "#5A8A2E",
    accent: "#A0E060",
    accentContract: "#FF8A65",
    accentManual: "#A0E060",
    accentApi: "#26C6DA",
    accentComponent: "#AB47BC",
    accentE2e: "#42A5F5",
    accentA11y: "#FFB74D",
    accentData: "#9CCC65",
    accentTs: "#3178C6",
    accentPy: "#3776AB",
    accentSol: "#737373",
    white: "#FFFFFF",
    textMuted: "#8B95A8",
    textSubtle: "#5A6373",
    boundaryLine: "#7CB342",
  },
  font: {
    sans: '"Inter", "Noto Sans JP", -apple-system, "Hiragino Kaku Gothic ProN", "Yu Gothic", "Segoe UI", sans-serif',
    mono: '"JetBrains Mono", "Noto Sans Mono CJK JP", "Menlo", "Courier New", monospace',
  },
  spacing: {
    xs: 8,
    sm: 16,
    md: 32,
    lg: 64,
    xl: 128,
  },
  text: {
    en: {
      productName: "kiwa",
      tagline: "Every test layer · One spec · Many languages",
      eyebrowProblem: "The Problem",
      headlineProblem: "Your test stack is scattered",
      problemSublineA: "Different runners for contract / API / UI / e2e",
      problemSublineB: "No single source of truth across stacks",
      eyebrowOneSpec: "The Idea",
      headlineOneSpec: "Layer 1 spec is the hub",
      oneSpecCaption: "9-column spec drives every Layer 2 generator",
      eyebrowSurfaces: "Test Surfaces",
      headlineSurfaces: "Six layers, one toolchain",
      eyebrowPolyglot: "Polyglot",
      headlinePolyglot: "TypeScript · Python · Solidity",
      polyglotCaption: "11 npm packages · 1 PyPI package · Foundry / Hardhat bridges",
      polyglotFutureLabel: "Rust / Go (planned)",
      eyebrowFlow: "Flow",
      headlineFlow: "Spec → parallel generators → green",
      flowStep1: "/kiwa-design — generates Layer 1 spec",
      flowStep2: "Layer 2 skills run in parallel",
      flowStep3: "All test layers pass",
      eyebrowQualityGates: "Quality Gates",
      headlineQualityGates: "Coverage + Mutation, enforced at release",
      gateCoverageCaption: "Lines ≥ 90 · Branches ≥ 80 · Functions ≥ 90",
      gateMutationCaption: "Per-package MSI, all ≥ 80%",
      eyebrowInstall: "Get Started",
      headlineInstall: "Install once, automate or write by hand",
      installLineClaude: "Path A — let Claude generate tests",
      installLineManual: "Path B — import @kiwa-test/core and write by hand",
      npmUrl: "npm install @kiwa-test/core",
      pypiUrl: "pip install kiwa-test-py",
      repoUrl: "github.com/cardene777/kiwa",
    },
    ja: {
      productName: "kiwa",
      tagline: "あらゆる test layer · 1 つの spec · どの言語でも",
      eyebrowProblem: "課題",
      headlineProblem: "test stack が散らばっている",
      problemSublineA: "contract / API / UI / e2e で runner がバラバラ",
      problemSublineB: "stack 横断の単一ソースが無い",
      eyebrowOneSpec: "発想",
      headlineOneSpec: "Layer 1 spec が hub",
      oneSpecCaption: "9 列 spec が全 Layer 2 generator を動かす",
      eyebrowSurfaces: "対応 layer",
      headlineSurfaces: "6 layer を 1 toolchain で",
      eyebrowPolyglot: "Polyglot",
      headlinePolyglot: "TypeScript · Python · Solidity",
      polyglotCaption: "11 npm package · 1 PyPI package · Foundry / Hardhat 連携",
      polyglotFutureLabel: "Rust / Go (構想中)",
      eyebrowFlow: "フロー",
      headlineFlow: "spec → 並列 generator → 全 PASS",
      flowStep1: "/kiwa-design で Layer 1 spec を生成",
      flowStep2: "Layer 2 skill を並列実行",
      flowStep3: "全 test layer が PASS",
      eyebrowQualityGates: "Quality Gate",
      headlineQualityGates: "Coverage + Mutation を release で物理 enforce",
      gateCoverageCaption: "Lines ≥ 90 · Branches ≥ 80 · Functions ≥ 90",
      gateMutationCaption: "package 別 MSI、 全 11 ≥ 80%",
      eyebrowInstall: "導入",
      headlineInstall: "1 コマンドで導入、 自動生成も手書きも",
      installLineClaude: "経路 A — Claude にテスト生成を任せる",
      installLineManual: "経路 B — @kiwa-test/core を import して手書き",
      npmUrl: "npm install @kiwa-test/core",
      pypiUrl: "pip install kiwa-test-py",
      repoUrl: "github.com/cardene777/kiwa",
    },
  },
  fps: 30,
} as const;

export const t = () => tokens.text[tokens.locale];
