type Locale = "en" | "ja";

export const tokens = {
  locale: "ja" as Locale,
  color: {
    bg: "#0F1419",
    bgGradientEnd: "#1A1F2E",
    primary: "#7CB342",
    primaryDark: "#5A8A2E",
    accent: "#A0E060",
    accentContract: "#FF8A65",
    accentManual: "#A0E060",
    accentApi: "#26C6DA",
    accentComponent: "#AB47BC",
    accentE2e: "#42A5F5",
    accentA11y: "#FFB74D",
    accentData: "#9CCC65",
    accentTs: "#3178C6",
    accentPy: "#3776AB",
    accentSol: "#737373",
    white: "#FFFFFF",
    textMuted: "#8B95A8",
    textSubtle: "#5A6373",
    boundaryLine: "#7CB342",
  },
  font: {
    sans: '"Inter", "Noto Sans JP", -apple-system, "Hiragino Kaku Gothic ProN", "Yu Gothic", "Segoe UI", sans-serif',
    mono: '"JetBrains Mono", "Noto Sans Mono CJK JP", "Menlo", "Courier New", monospace',
  },
  spacing: {
    xs: 8,
    sm: 16,
    md: 32,
    lg: 64,
    xl: 128,
  },
  text: {
    en: {
      productName: "kiwa",
      tagline: "Every test layer · One spec · Many languages",
      eyebrowProblem: "The Problem",
      headlineProblem: "Your test stack is scattered",
      problemSublineA: "Different runners for contract / API / UI / e2e",
      problemSublineB: "No single source of truth across stacks",
      eyebrowOneSpec: "The Idea",
      headlineOneSpec: "Layer 1 spec is the hub",
      oneSpecCaption: "9-column spec drives every Layer 2 generator",
      eyebrowSurfaces: "Test Surfaces",
      headlineSurfaces: "Six layers, one toolchain",
      eyebrowFrameworks: "Framework adapters",
      headlineFrameworks: "8 adapters, one ui package",
      eyebrowPolyglot: "Polyglot",
      headlinePolyglot: "TypeScript · Python · Solidity",
      polyglotCaption: "11 npm packages · 1 PyPI package · Foundry / Hardhat bridges",
      polyglotFutureLabel: "Rust / Go (planned)",
      eyebrowSkillChain: "Skill chain",
      headlineSkillChain: "8 skills · spec to test, end to end",
      skillChainCaption: "Layer 1 design + Layer 2 generators + reviewer",
      eyebrowFlow: "Flow",
      headlineFlow: "Spec → parallel generators → green",
      flowStep1: "/kiwa-design — generates Layer 1 spec",
      flowStep2: "Layer 2 skills run in parallel",
      flowStep3: "All test layers pass",
      eyebrowQualityGates: "Quality Gates",
      headlineQualityGates: "Coverage + Mutation, enforced at release",
      gateCoverageCaption: "Lines ≥ 90 · Branches ≥ 80 · Functions ≥ 90",
      gateMutationCaption: "Per-package MSI, all ≥ 80%",
      eyebrowPackages: "Packages",
      headlinePackages: "12 packages on npm + PyPI",
      packagesCaption: "11 npm × @kiwa-test + 1 PyPI × kiwa-test-py",
      eyebrowInstall: "Get Started",
      headlineInstall: "Install once, automate or write by hand",
      installLineClaude: "Path A — let Claude generate tests",
      installLineManual: "Path B — import @kiwa-test/core and write by hand",
      npmUrl: "npm install @kiwa-test/core",
      pypiUrl: "pip install kiwa-test-py",
      repoUrl: "github.com/cardene777/kiwa",
      v8HookLine1: "Tests are written",
      v8HookLine2: "by AI now.",
      v8IdeaLine1: "Write the spec.",
      v8IdeaLine2: "AI writes the tests.",
      v8IdeaSub: "1 spec → contract · api · ui · e2e · a11y · visual",
      v8ScaleEyebrow: "From one spec",
      v8ScaleNumA: "6",
      v8ScaleLabelA: "test surfaces",
      v8ScaleNumB: "3",
      v8ScaleLabelB: "languages",
      v8ScaleNumC: "8",
      v8ScaleLabelC: "skills, chained",
      v8ScaleFooter: "Foundry · Hardhat · Vitest · Playwright · msw",
      v8SetupEyebrow: "Setup",
      v8SetupHeadline: "One install. Then describe.",
      v8GenerateEyebrow: "Generate",
      v8GenerateHeadline: "AI writes every layer in parallel",
      v8GenerateAi: "✓ Spec parsed. Forge / Vitest / Playwright generators running in parallel.",
      v8PassEyebrow: "Ship",
      v8PassHeadline: "You wrote the spec.\nAI shipped the tests.",
      v8PassCta: "npm install @kiwa-test/core",
      v8PassRepo: "github.com/cardene777/kiwa",
      v9BrandName: "kiwa",
      v9BrandTagline: "Tests with no blind spots, generated.",
      v9ExplainHeadline: "kiwa generates tests with no blind spots.",
      v9ExplainSub: "11 perspectives × 9 sections, unified format.",
      v9MethodHeadline: "11 perspectives × 9 sections",
      v9MethodSub: "unified spec format",
      v9MethodChips: ["normal","abnormal","boundary","state","authz","validation","idempotency","concurrency","performance","security","regression"],
      v9CoverageHeadline: "11 perspectives across every layer",
      v9CoverageSurfaces: ["contract","api","ui","e2e","a11y","visual"],
      v9CoverageFooter: "Foundry · Hardhat · Vitest · Playwright · msw",
      v9FlowEyebrow: "Flow",
      v9FlowHeadline: "Spec → tests → review, in a single skill chain",
      v9FlowTerm1Title: "/kiwa-design",
      v9FlowTerm1Cmd: "claude /kiwa-design tokenGating",
      v9FlowTerm1Log: "✓ Spec written: tests/spec/contract/test-spec-tokenGating.md",
      v9FlowTerm2aTitle: "/kiwa-forge",
      v9FlowTerm2aCmd: "claude /kiwa-forge tokenGating",
      v9FlowTerm2aLog: "✓ 9 passed · forge test (1.2s)",
      v9FlowTerm2bTitle: "/kiwa-vitest",
      v9FlowTerm2bCmd: "claude /kiwa-vitest tokenGating",
      v9FlowTerm2bLog: "✓ 14 passed · vitest run (0.8s)",
      v9FlowTerm2cTitle: "/kiwa-play",
      v9FlowTerm2cCmd: "claude /kiwa-play tokenGating",
      v9FlowTerm2cLog: "✓ 4 passed · playwright test (2.1s)",
      v9FlowTerm3Title: "/kiwa-review",
      v9FlowTerm3Cmd: "claude /kiwa-review tokenGating",
      v9FlowTerm3Log: "✓ 11/11 perspectives covered.",
      v9PathsEyebrow: "Two paths",
      v9PathsHeadline: "AI accelerates. You can still write by hand.",
      v9PathsAiTitle: "AI generation",
      v9PathsAiLine1: "/kiwa-design generates spec",
      v9PathsAiLine2: "/kiwa-forge generates tests",
      v9PathsAiLine3: "AI fills the 11 perspectives",
      v9PathsManualTitle: "Hand-written",
      v9PathsManualLine1: "Read 9-section spec template",
      v9PathsManualLine2: "Write tests with @kiwa-test/core",
      v9PathsManualLine3: "Same coverage. Same quality.",
      v9CtaCmd: "npm install @kiwa-test/core",
      v9CtaRepo: "github.com/cardene777/kiwa",
    },
    ja: {
      productName: "kiwa",
      tagline: "あらゆる test layer · 1 つの spec · どの言語でも",
      eyebrowProblem: "課題",
      headlineProblem: "test stack が散らばっている",
      problemSublineA: "contract / API / UI / e2e で runner がバラバラ",
      problemSublineB: "stack 横断の単一ソースが無い",
      eyebrowOneSpec: "発想",
      headlineOneSpec: "Layer 1 spec が hub",
      oneSpecCaption: "9 列 spec が全 Layer 2 generator を動かす",
      eyebrowSurfaces: "対応 layer",
      headlineSurfaces: "6 layer を 1 toolchain で",
      eyebrowFrameworks: "framework adapter",
      headlineFrameworks: "1 package で 8 adapter 対応",
      eyebrowPolyglot: "Polyglot",
      headlinePolyglot: "TypeScript · Python · Solidity",
      polyglotCaption: "11 npm package · 1 PyPI package · Foundry / Hardhat 連携",
      polyglotFutureLabel: "Rust / Go (構想中)",
      eyebrowSkillChain: "skill chain",
      headlineSkillChain: "8 skill が spec → test を一気通貫で",
      skillChainCaption: "Layer 1 設計 + Layer 2 生成器 + reviewer",
      eyebrowFlow: "フロー",
      headlineFlow: "spec → 並列 generator → 全 PASS",
      flowStep1: "/kiwa-design で Layer 1 spec を生成",
      flowStep2: "Layer 2 skill を並列実行",
      flowStep3: "全 test layer が PASS",
      eyebrowQualityGates: "Quality Gate",
      headlineQualityGates: "Coverage + Mutation を release で物理 enforce",
      gateCoverageCaption: "Lines ≥ 90 · Branches ≥ 80 · Functions ≥ 90",
      gateMutationCaption: "package 別 MSI、 全 11 ≥ 80%",
      eyebrowPackages: "Package",
      headlinePackages: "12 package を npm + PyPI で公開",
      packagesCaption: "11 npm × @kiwa-test + 1 PyPI × kiwa-test-py",
      eyebrowInstall: "導入",
      headlineInstall: "1 コマンドで導入、 自動生成も手書きも",
      installLineClaude: "経路 A — Claude にテスト生成を任せる",
      installLineManual: "経路 B — @kiwa-test/core を import して手書き",
      npmUrl: "npm install @kiwa-test/core",
      pypiUrl: "pip install kiwa-test-py",
      repoUrl: "github.com/cardene777/kiwa",
      v8HookLine1: "test は AI が",
      v8HookLine2: "書く時代。",
      v8IdeaLine1: "あなたは spec を書く。",
      v8IdeaLine2: "AI が test を書く。",
      v8IdeaSub: "1 spec → contract · api · ui · e2e · a11y · visual",
      v8ScaleEyebrow: "1 つの spec から",
      v8ScaleNumA: "6",
      v8ScaleLabelA: "test surface",
      v8ScaleNumB: "3",
      v8ScaleLabelB: "言語",
      v8ScaleNumC: "8",
      v8ScaleLabelC: "skill chain",
      v8ScaleFooter: "Foundry · Hardhat · Vitest · Playwright · msw",
      v8SetupEyebrow: "導入",
      v8SetupHeadline: "1 度入れて、 仕様を書くだけ。",
      v8GenerateEyebrow: "生成",
      v8GenerateHeadline: "AI が全層の test を並列生成",
      v8GenerateAi: "✓ spec 解析完了。 Forge / Vitest / Playwright generator が並列で稼働中。",
      v8PassEyebrow: "出荷",
      v8PassHeadline: "あなたは spec を書く。\nAI が test を出荷する。",
      v8PassCta: "npm install @kiwa-test/core",
      v8PassRepo: "github.com/cardene777/kiwa",
      v9BrandName: "kiwa",
      v9BrandTagline: "抜け漏れない test を生成する。",
      v9ExplainHeadline: "kiwa は抜け漏れない test を生成する tool です。",
      v9ExplainSub: "11 観点 × 9 section 統一フォーマット",
      v9MethodHeadline: "11 観点 × 9 section",
      v9MethodSub: "統一フォーマット",
      v9MethodChips: ["正常","異常","境界","状態","権限","バリデーション","冪等","並行","性能","セキュリティ","回帰"],
      v9CoverageHeadline: "全 layer で 11 観点を網羅",
      v9CoverageSurfaces: ["contract","api","ui","e2e","a11y","visual"],
      v9CoverageFooter: "Foundry · Hardhat · Vitest · Playwright · msw",
      v9FlowEyebrow: "Flow",
      v9FlowHeadline: "spec → test → review を 1 つの skill chain で",
      v9FlowTerm1Title: "/kiwa-design",
      v9FlowTerm1Cmd: "claude /kiwa-design tokenGating",
      v9FlowTerm1Log: "✓ spec 作成完了: tests/spec/contract/test-spec-tokenGating.md",
      v9FlowTerm2aTitle: "/kiwa-forge",
      v9FlowTerm2aCmd: "claude /kiwa-forge tokenGating",
      v9FlowTerm2aLog: "✓ 9 passed · forge test (1.2s)",
      v9FlowTerm2bTitle: "/kiwa-vitest",
      v9FlowTerm2bCmd: "claude /kiwa-vitest tokenGating",
      v9FlowTerm2bLog: "✓ 14 passed · vitest run (0.8s)",
      v9FlowTerm2cTitle: "/kiwa-play",
      v9FlowTerm2cCmd: "claude /kiwa-play tokenGating",
      v9FlowTerm2cLog: "✓ 4 passed · playwright test (2.1s)",
      v9FlowTerm3Title: "/kiwa-review",
      v9FlowTerm3Cmd: "claude /kiwa-review tokenGating",
      v9FlowTerm3Log: "✓ 11/11 観点を網羅",
      v9PathsEyebrow: "2 つの経路",
      v9PathsHeadline: "AI は加速器。 手でも書ける。",
      v9PathsAiTitle: "AI 生成経路",
      v9PathsAiLine1: "/kiwa-design で spec 生成",
      v9PathsAiLine2: "/kiwa-forge で test 生成",
      v9PathsAiLine3: "AI が 11 観点を埋める",
      v9PathsManualTitle: "手書き経路",
      v9PathsManualLine1: "9 section spec を Read",
      v9PathsManualLine2: "@kiwa-test/core で test を書く",
      v9PathsManualLine3: "同じ網羅率。 同じ品質。",
      v9CtaCmd: "npm install @kiwa-test/core",
      v9CtaRepo: "github.com/cardene777/kiwa",
    },
  },
  fps: 30,
} as const;

export const t = () => tokens.text[tokens.locale];
