// Generated by /kiwa-nextjs --layer nextjs-rsc (Issue #494) from a 9-column Layer 1 spec.

import { describe, expect, it } from 'vitest';
import {
  renderServerComponent,
  findAll,
  textContent,
  NOT_FOUND_SYMBOL,
  type RscElement,
} from '@kiwa-test/nextjs';
import { UserPage, UserList } from '../src/user-page.js';

describe('UserPage', () => {
  it('T-RSC-001 正常系: existing user renders name + id + slug', async () => {
    const { tree, signal, error } = await renderServerComponent({
      component: UserPage,
      props: { params: { slug: 'alice' } },
    });
    expect(error).toBeUndefined();
    expect(signal).toBeNull();
    expect(textContent(tree)).toContain('Alice');
    expect(textContent(tree)).toContain('id=1');
    expect(textContent(tree)).toContain('slug=alice');
  });

  it('T-RSC-002 unknown slug: throws kiwa.next.rsc.notFound signal', async () => {
    const { tree, signal, error } = await renderServerComponent({
      component: UserPage,
      props: { params: { slug: 'nobody' } },
    });
    expect(tree).toBeNull();
    expect(error).toBeUndefined();
    expect(signal).not.toBeNull();
    expect((signal as { [NOT_FOUND_SYMBOL]?: true })[NOT_FOUND_SYMBOL]).toBe(true);
  });

  it('T-RSC-003 element structure: data-testid leaves are addressable', async () => {
    const { tree } = await renderServerComponent({
      component: UserPage,
      props: { params: { slug: 'bob' } },
    });
    const id = findAll(tree, (n) => (n.props as { 'data-testid'?: string })['data-testid'] === 'user-id');
    expect(id).toHaveLength(1);
    expect(textContent(id[0] as RscElement)).toBe('id=2');
  });
});

describe('UserList', () => {
  it('T-RSC-004 unfiltered: all users rendered as <li>', async () => {
    const { tree } = await renderServerComponent({
      component: UserList,
      props: { searchParams: {} },
    });
    const items = findAll(tree, (n) => n.type === 'li');
    expect(items).toHaveLength(2);
  });

  it('T-RSC-005 searchParams.q filters case-insensitively', async () => {
    const { tree } = await renderServerComponent({
      component: UserList,
      props: { searchParams: { q: 'BO' } },
    });
    const items = findAll(tree, (n) => n.type === 'li');
    expect(items).toHaveLength(1);
    expect(textContent(items[0] as RscElement)).toBe('Bob');
  });
});
