/**
 * Mutation testing config for @kiwa-lab/auth.
 * Threshold: framework tier (high 70 / low 60 / break 50) — auth adapter wraps
 * NextAuth v5 / Lucia v3 / Better Auth / Clerk / Auth0 / Supabase, includes
 * SSR / RSC / hydration paths + provider mocks with partial fidelity.
 * SSOT: docs/quality/mutation-thresholds.md § framework tier.
 *
 * Every implementation file (#1980). Until then the list held `adapter.js` /
 * `providers.js` / `session.js` — 288 lines of 14,187, the lowest ratio in the
 * repo at 2.0 %, and the sole evidence behind the doc's claim that the large
 * group needed its own test-writing plan.
 *
 * Measured, that claim did not hold here: 6,171 mutants at 79.89 % covered MSI,
 * ten points clear of the tier, with no test written. The provider trees
 * (auth0 / clerk / supabase / oidc / oauth21 / passkey / webauthn) carry their
 * own suites; nothing had ever thrown a mutant at them.
 */
export default {
  packageManager: 'pnpm',
  testRunner: 'vitest',
  testRunnerNodeArgs: ['--max-old-space-size=4096'],
  plugins: ['@stryker-mutator/vitest-runner'],
  vitest: { configFile: 'vitest.stryker.config.mjs' },
  mutate: [
    '.vitest-dist/src/adapter.js',
    '.vitest-dist/src/auth0/jwt.js',
    '.vitest-dist/src/auth0/setup-auth0-env.js',
    '.vitest-dist/src/auth0/store.js',
    '.vitest-dist/src/auth0/types.js',
    '.vitest-dist/src/better-auth/adapter.js',
    '.vitest-dist/src/better-auth/password.js',
    '.vitest-dist/src/better-auth/providers.js',
    '.vitest-dist/src/better-auth/session.js',
    '.vitest-dist/src/better-auth/setup-better-auth-env.js',
    '.vitest-dist/src/better-auth/totp.js',
    '.vitest-dist/src/better-auth/types.js',
    '.vitest-dist/src/better-auth/verification.js',
    '.vitest-dist/src/clerk/jwt.js',
    '.vitest-dist/src/clerk/setup-clerk-env.js',
    '.vitest-dist/src/clerk/store.js',
    '.vitest-dist/src/clerk/types.js',
    '.vitest-dist/src/lucia/adapter.js',
    '.vitest-dist/src/lucia/password.js',
    '.vitest-dist/src/lucia/providers.js',
    '.vitest-dist/src/lucia/session.js',
    '.vitest-dist/src/lucia/setup-lucia-env.js',
    '.vitest-dist/src/lucia/types.js',
    '.vitest-dist/src/oauth21/authorization-server.js',
    '.vitest-dist/src/oauth21/dpop.js',
    '.vitest-dist/src/oauth21/pkce.js',
    '.vitest-dist/src/oauth21/refresh-rotation.js',
    '.vitest-dist/src/oauth21/setup-oauth21-env.js',
    '.vitest-dist/src/oauth21/types.js',
    '.vitest-dist/src/oidc/dcr.js',
    '.vitest-dist/src/oidc/discovery.js',
    '.vitest-dist/src/oidc/federation.js',
    '.vitest-dist/src/oidc/id-token.js',
    '.vitest-dist/src/oidc/jwks.js',
    '.vitest-dist/src/oidc/setup-oidc-env.js',
    '.vitest-dist/src/oidc/types.js',
    '.vitest-dist/src/passkey/caBLE/ble-handshake.js',
    '.vitest-dist/src/passkey/caBLE/hybrid-transport.js',
    '.vitest-dist/src/passkey/caBLE/qr-code.js',
    '.vitest-dist/src/passkey/caBLE/types.js',
    '.vitest-dist/src/passkey/caBLE/websocket-tunnel.js',
    '.vitest-dist/src/passkey/credential-sync.js',
    '.vitest-dist/src/passkey/platform.js',
    '.vitest-dist/src/passkey/roaming.js',
    '.vitest-dist/src/passkey/setup-passkey-env.js',
    '.vitest-dist/src/passkey/sync-fabric.js',
    '.vitest-dist/src/passkey/types.js',
    '.vitest-dist/src/providers.js',
    '.vitest-dist/src/semantics/auth-continuity.js',
    '.vitest-dist/src/semantics/auth-telemetry.js',
    '.vitest-dist/src/semantics/conditional-ui.js',
    '.vitest-dist/src/semantics/continuous-auth.js',
    '.vitest-dist/src/semantics/cross-device-flow.js',
    '.vitest-dist/src/semantics/device-bound-passkey.js',
    '.vitest-dist/src/semantics/fidelity.js',
    '.vitest-dist/src/semantics/risk-based-auth.js',
    '.vitest-dist/src/semantics/session-hijack-detect.js',
    '.vitest-dist/src/semantics/session-lifecycle-orchestrator.js',
    '.vitest-dist/src/semantics/step-up-mfa.js',
    '.vitest-dist/src/semantics/types.js',
    '.vitest-dist/src/session.js',
    '.vitest-dist/src/setup-nextauth-env.js',
    '.vitest-dist/src/supabase-advanced/mfa.js',
    '.vitest-dist/src/supabase-advanced/rls.js',
    '.vitest-dist/src/supabase-advanced/saml.js',
    '.vitest-dist/src/supabase-advanced/setup-supabase-advanced-env.js',
    '.vitest-dist/src/supabase-advanced/siwe.js',
    '.vitest-dist/src/supabase-advanced/types.js',
    '.vitest-dist/src/supabase/jwt.js',
    '.vitest-dist/src/supabase/setup-supabase-auth-env.js',
    '.vitest-dist/src/supabase/store.js',
    '.vitest-dist/src/supabase/types.js',
    '.vitest-dist/src/types.js',
    '.vitest-dist/src/webauthn/assertion.js',
    '.vitest-dist/src/webauthn/authenticator.js',
    '.vitest-dist/src/webauthn/creation.js',
    '.vitest-dist/src/webauthn/encoding.js',
    '.vitest-dist/src/webauthn/setup-webauthn-env.js',
    '.vitest-dist/src/webauthn/types.js',
  ],
  thresholds: { high: 70, low: 60, break: 50 },
  ignorePatterns: ['dist/**', 'coverage/**', 'node_modules/**'],
  reporters: ['progress-append-only', 'html', 'clear-text', 'json'],
  jsonReporter: { fileName: 'mutation-report/mutation.json' },
  htmlReporter: { fileName: 'mutation-report/index.html' },
  warnings: { unknownOptions: false },
  concurrency: 4,
};
