import type { LeanSpecOutput, OrchestratorSpec } from './types.js';

const toPascalCase = (input: string): string =>
  input
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1))
    .join('');

const toLeanConstructor = (input: string): string => toPascalCase(input);

/**
 * Generate a Lean 4 spec for a kiwa lifecycle-orchestrator state machine.
 *
 * Output layout:
 *
 * ```lean
 * namespace {Namespace}
 *
 * inductive State where
 *   | Init : State
 *   | Authed : State
 *   ...
 * deriving DecidableEq, Repr
 *
 * inductive Event where
 *   | AuthSucceeded : Event
 *   ...
 * deriving DecidableEq, Repr
 *
 * def dispatch : State → Event → State
 *   | .Init, .AuthSucceeded => .Authed
 *   | s, _ => s  -- invalid transition falls through to identity
 *
 * theorem dispatch_total (s : State) (e : Event) : ∃ s', dispatch s e = s' := by
 *   exact ⟨dispatch s e, rfl⟩
 * ```
 */
export function generateLeanSpec(spec: OrchestratorSpec): LeanSpecOutput {
  const { moduleName, namespace, states, events, transitions } = spec;

  if (states.length === 0) {
    throw new Error('generateLeanSpec: at least one state is required');
  }
  if (events.length === 0) {
    throw new Error('generateLeanSpec: at least one event is required');
  }

  const stateConstructors = states.map(toLeanConstructor);
  const eventConstructors = events.map(toLeanConstructor);

  const validPairs = new Set<string>();
  const transitionLines: string[] = [];
  for (const t of transitions) {
    if (!states.includes(t.from)) {
      throw new Error(`generateLeanSpec: unknown state in transition.from: ${t.from}`);
    }
    if (!events.includes(t.event)) {
      throw new Error(`generateLeanSpec: unknown event in transition.event: ${t.event}`);
    }
    if (!states.includes(t.to)) {
      throw new Error(`generateLeanSpec: unknown state in transition.to: ${t.to}`);
    }
    const key = `${t.from}::${t.event}`;
    if (validPairs.has(key)) {
      throw new Error(`generateLeanSpec: duplicate transition ${key}`);
    }
    validPairs.add(key);
    transitionLines.push(
      `  | .${toLeanConstructor(t.from)}, .${toLeanConstructor(t.event)} => .${toLeanConstructor(t.to)}`,
    );
  }

  const cellCount = states.length * events.length;
  const validCount = validPairs.size;
  const invalidCount = cellCount - validCount;

  const stateBlock = stateConstructors.map((c) => `  | ${c} : State`).join('\n');
  const eventBlock = eventConstructors.map((c) => `  | ${c} : Event`).join('\n');
  const dispatchFallthrough = `  | s, _ => s -- invalid transition: stay in current state (identity)`;

  const source = `-- Generated by @kiwa-lab/lean v0.1 — do not edit by hand.
-- Spec: ${moduleName} (${states.length} states × ${events.length} events = ${cellCount} cells)
-- Valid transitions: ${validCount}  Invalid (identity): ${invalidCount}

namespace ${namespace}

inductive State where
${stateBlock}
deriving DecidableEq, Repr

inductive Event where
${eventBlock}
deriving DecidableEq, Repr

def dispatch : State → Event → State
${transitionLines.join('\n')}
${dispatchFallthrough}

-- Totality theorem: dispatch is defined for every (state, event) pair.
-- Proof is by construction — Lean's pattern-match exhaustiveness checker
-- guarantees the identity fallthrough covers every unlisted cell.
theorem dispatch_total (s : State) (e : Event) : ∃ s', dispatch s e = s' := by
  exact ⟨dispatch s e, rfl⟩

end ${namespace}
`;

  return {
    source,
    path: `${moduleName}.lean`,
    meta: {
      stateCount: states.length,
      eventCount: events.length,
      cellCount,
      validTransitionCount: validCount,
      invalidTransitionCount: invalidCount,
    },
  };
}
