import { isInvalid, type LeanSpecOutput, type OrchestratorSpec, type Transition } from './types.js';

const toPascalCase = (input: string): string =>
  input
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1))
    .join('');

/** Theorem names are Lean identifiers, so `savepoint-nested` becomes `savepoint_nested`. */
const toSnakeCase = (input: string): string =>
  input
    .split(/[-\s]+/)
    .filter(Boolean)
    .join('_')
    .toLowerCase();

const cellKey = (state: string, event: string): string => `${state}::${event}`;

/** How many undeclared cells to name before saying "and N more". */
const MAX_REPORTED_CELLS = 8;

/**
 * Generate a Lean 4 spec for a lifecycle-orchestrator state machine.
 *
 * The generated file lists every `(state, event)` cell and has no catch-all. That
 * is deliberate: Lean refuses a non-exhaustive match, so the exhaustiveness of the
 * table is checked by Lean rather than asserted by a theorem that cannot fail.
 *
 * ```lean
 * inductive Step where
 *   | to : State → Step
 *   | invalid : Step
 *
 * def dispatch : State → Event → Step
 *   | .Beginning, .BeginCompleted => .to .Active
 *   | .Beginning, .QueryExecuted  => .invalid
 *   ...
 *
 * theorem aborted_absorbing : ∀ e, dispatch .Aborted e = .invalid := by
 *   intro e; cases e <;> rfl
 *
 * theorem beginning_can_leave : ∃ e, escapes .Beginning e = true :=
 *   ⟨.BeginCompleted, rfl⟩
 * ```
 *
 * The theorems say things a reader could otherwise get wrong: which states are
 * terminal, which can actually be left, which accept events and go nowhere, and
 * which paths reach which states. Their proofs are mechanical because the
 * generator already knows the table, and they fail to compile if it is misread.
 */
export function generateLeanSpec(spec: OrchestratorSpec): LeanSpecOutput {
  const { moduleName, namespace, states, events, transitions, unspecified = 'error' } = spec;

  if (states.length === 0) {
    throw new Error('generateLeanSpec: at least one state is required');
  }
  if (events.length === 0) {
    throw new Error('generateLeanSpec: at least one event is required');
  }

  const table = buildTable(states, events, transitions);
  const undeclared = findUndeclared(states, events, table);

  if (undeclared.length > 0) {
    if (unspecified === 'error') throw undeclaredError(undeclared);
    for (const cell of undeclared) table.set(cell, null);
  }

  const validCount = [...table.values()].filter((target) => target !== null).length;
  const cellCount = states.length * events.length;

  const terminalStates = states.filter((state) =>
    events.every((event) => table.get(cellKey(state, event)) === null),
  );
  // A sink accepts events and never leaves, because every valid cell loops back.
  // It is not terminal, and it is not a state anything escapes from either.
  const sinkStates = states.filter(
    (state) =>
      !terminalStates.includes(state) &&
      events.every((event) => {
        const target = table.get(cellKey(state, event));
        return target === null || target === undefined || target === state;
      }),
  );
  if (spec.terminal !== undefined) {
    assertTerminalsAgree(states, spec.terminal, terminalStates);
  }

  const paths = spec.initial === undefined ? undefined : reachabilityPaths(spec.initial, states, events, table);

  const dispatchLines = renderDispatch(states, events, table);
  const blocks = [
    ...renderTheorems(states, events, table, terminalStates),
    ...(spec.initial === undefined || paths === undefined
      ? []
      : renderReachability(spec.initial, paths)),
  ];
  const stepsDef = spec.initial === undefined ? '' : `\n${STEPS_DEF}`;
  const theorems = blocks.length === 0 ? '\n' : `\n${blocks.join('\n\n')}\n\n`;

  const source = `-- Generated by @kiwa-lab/lean — do not edit by hand.
-- Spec: ${moduleName} (${states.length} states × ${events.length} events = ${cellCount} cells)
-- Valid transitions: ${validCount}  Rejected: ${cellCount - validCount}
--
-- Every cell is listed and there is no catch-all, so Lean's exhaustiveness
-- checker is what proves the table is complete. Removing a line is a compile
-- error naming the cell, not a silent fallthrough.

namespace ${namespace}

inductive State where
${states.map((s) => `  | ${toPascalCase(s)} : State`).join('\n')}
deriving DecidableEq, Repr

inductive Event where
${events.map((e) => `  | ${toPascalCase(e)} : Event`).join('\n')}
deriving DecidableEq, Repr

/-- The result of feeding an event to a state: either a next state, or a
rejection. A self-loop steps back to the same state, which is a decision, and is
therefore distinguishable from a rejection. -/
inductive Step where
  | to : State → Step
  | invalid : Step
deriving DecidableEq, Repr

def dispatch : State → Event → Step
${dispatchLines.join('\n')}

/-- Whether an event moves the machine to a different state. A self-loop does
not: it is accepted, and it goes nowhere. -/
def escapes (s : State) (e : Event) : Bool :=
  match dispatch s e with
  | .to s' => !(decide (s' = s))
  | .invalid => false
${stepsDef}${theorems}end ${namespace}
`;

  const meta: LeanSpecOutput['meta'] = {
    stateCount: states.length,
    eventCount: events.length,
    cellCount,
    validTransitionCount: validCount,
    invalidTransitionCount: cellCount - validCount,
    terminalStates,
    sinkStates,
  };
  if (paths !== undefined) meta.reachablePaths = Object.fromEntries(paths);

  return { source, path: `${moduleName}.lean`, meta };
}

/**
 * Feed a sequence of events, stopping at the first rejection. A reachability
 * theorem is a claim about this function, and `rfl` computes it.
 */
const STEPS_DEF = `/-- Feed a sequence of events, stopping at the first rejection. -/
def steps : State → List Event → Step
  | s, [] => .to s
  | s, e :: rest =>
    match dispatch s e with
    | .to s' => steps s' rest
    | .invalid => .invalid
`;

/** `null` marks a rejected cell; a string is the target state. */
type Table = Map<string, string | null>;

function buildTable(
  states: readonly string[],
  events: readonly string[],
  transitions: readonly Transition[],
): Table {
  const table: Table = new Map();
  for (const t of transitions) {
    if (!states.includes(t.from)) {
      throw new Error(`generateLeanSpec: unknown state in transition.from: ${t.from}`);
    }
    if (!events.includes(t.event)) {
      throw new Error(`generateLeanSpec: unknown event in transition.event: ${t.event}`);
    }
    const key = cellKey(t.from, t.event);
    if (table.has(key)) {
      throw new Error(`generateLeanSpec: duplicate transition ${key}`);
    }
    if (isInvalid(t)) {
      table.set(key, null);
      continue;
    }
    if (!states.includes(t.to)) {
      throw new Error(`generateLeanSpec: unknown state in transition.to: ${t.to}`);
    }
    table.set(key, t.to);
  }
  return table;
}

function findUndeclared(
  states: readonly string[],
  events: readonly string[],
  table: Table,
): string[] {
  const missing: string[] = [];
  for (const state of states) {
    for (const event of events) {
      const key = cellKey(state, event);
      if (!table.has(key)) missing.push(key);
    }
  }
  return missing;
}

/**
 * Undeclared cells are named, because "the table is incomplete" is not actionable
 * and "beginning::query-executed is undecided" is.
 */
function undeclaredError(undeclared: readonly string[]): Error {
  const shown = undeclared
    .slice(0, MAX_REPORTED_CELLS)
    .map((cell) => `  ${cell.replace('::', ' + ')}`)
    .join('\n');
  const rest =
    undeclared.length > MAX_REPORTED_CELLS
      ? `\n  ...and ${undeclared.length - MAX_REPORTED_CELLS} more`
      : '';
  return new Error(
    `generateLeanSpec: ${undeclared.length} (state, event) cell(s) are undeclared:\n${shown}${rest}\n\n` +
      'Give each a target, or mark it { invalid: true }. Pass `unspecified: "invalid"` ' +
      'to reject every unmentioned cell instead.',
  );
}

/**
 * Check the author's belief about which states are terminal against the table.
 *
 * Both directions are a disagreement worth stopping for. A state declared
 * terminal that has a way out means the table grew an exit nobody meant to add.
 * A state with no way out that was not declared means the machine can get stuck
 * somewhere the author did not think it could.
 */
function assertTerminalsAgree(
  states: readonly string[],
  declared: readonly string[],
  actual: readonly string[],
): void {
  const unknown = declared.filter((state) => !states.includes(state));
  if (unknown.length > 0) {
    throw new Error(`generateLeanSpec: unknown state in terminal: ${unknown.join(', ')}`);
  }

  const claimedButLeaves = declared.filter((state) => !actual.includes(state));
  const stuckButUnclaimed = actual.filter((state) => !declared.includes(state));

  const problems: string[] = [];
  for (const state of claimedButLeaves) {
    problems.push(`  ${state} is declared terminal but the table gives it a way out`);
  }
  for (const state of stuckButUnclaimed) {
    problems.push(`  ${state} has no way out but is not declared terminal`);
  }
  if (problems.length > 0) {
    throw new Error(
      `generateLeanSpec: the table and the declared terminal states disagree:\n${problems.join('\n')}`,
    );
  }
}

/**
 * A shortest path of events from `initial` to every other state, by breadth-first
 * search over the valid transitions. Shortest so the witness a reader sees is the
 * simplest one, and so the emitted theorem stays small.
 *
 * A state with no path cannot be given a theorem, and that is the finding: a
 * state nothing reaches exists only in the type.
 */
function reachabilityPaths(
  initial: string,
  states: readonly string[],
  events: readonly string[],
  table: Table,
): Map<string, string[]> {
  if (!states.includes(initial)) {
    throw new Error(`generateLeanSpec: unknown state in initial: ${initial}`);
  }

  const paths = new Map<string, string[]>([[initial, []]]);
  const queue: string[] = [initial];
  while (queue.length > 0) {
    const state = queue.shift() as string;
    const path = paths.get(state) as string[];
    for (const event of events) {
      const target = table.get(cellKey(state, event));
      if (target === null || target === undefined) continue;
      if (paths.has(target)) continue;
      paths.set(target, [...path, event]);
      queue.push(target);
    }
  }

  const unreachable = states.filter((state) => !paths.has(state));
  if (unreachable.length > 0) {
    throw new Error(
      `generateLeanSpec: ${unreachable.length} state(s) cannot be reached from "${initial}":\n` +
        unreachable.map((state) => `  ${state}`).join('\n') +
        '\n\nGive each a transition that reaches it, or remove it from the machine.',
    );
  }

  paths.delete(initial);
  return paths;
}

/** One theorem per state, each carrying the path of events that reaches it. */
function renderReachability(initial: string, paths: Map<string, string[]>): string[] {
  const blocks: string[] = [];
  for (const [state, path] of paths) {
    const events = path.map((event) => `.${toPascalCase(event)}`).join(', ');
    blocks.push(
      `/-- State ${state} is reachable from ${initial}. -/
theorem ${toSnakeCase(state)}_reachable : steps .${toPascalCase(initial)} [${events}] = .to .${toPascalCase(state)} := rfl`,
    );
  }
  return blocks;
}

function renderDispatch(
  states: readonly string[],
  events: readonly string[],
  table: Table,
): string[] {
  const statePad = Math.max(...states.map((s) => toPascalCase(s).length));
  const eventPad = Math.max(...events.map((e) => toPascalCase(e).length));

  const lines: string[] = [];
  for (const state of states) {
    for (const event of events) {
      const target = table.get(cellKey(state, event));
      const left = `.${toPascalCase(state)},`.padEnd(statePad + 2);
      const right = `.${toPascalCase(event)}`.padEnd(eventPad + 1);
      const result = target === null || target === undefined ? '.invalid' : `.to .${toPascalCase(target)}`;
      lines.push(`  | ${left} ${right} => ${result}`);
    }
  }
  return lines;
}

/**
 * Three families of theorem, all mechanical and all falsifiable.
 *
 * A terminal state rejects every event. A state that can leave has an event that
 * moves it elsewhere, and the witness is the first such cell in event order.
 *
 * Between the two sits the sink: a state that accepts events and goes nowhere,
 * because every valid cell loops back to itself. `dlq + dlq-inspected => dlq` is
 * not a rejection, so the state is not terminal, and yet nothing ever leaves. A
 * theorem asking only for a valid event would be satisfied by that self-loop and
 * would say the state has a way out, which is the opposite of true.
 */
function renderTheorems(
  states: readonly string[],
  events: readonly string[],
  table: Table,
  terminalStates: readonly string[],
): string[] {
  const blocks: string[] = [];

  for (const state of terminalStates) {
    blocks.push(
      `/-- State ${state} is terminal: no event leads anywhere from it. -/
theorem ${toSnakeCase(state)}_absorbing : ∀ e, dispatch .${toPascalCase(state)} e = .invalid := by
  intro e; cases e <;> rfl`,
    );
  }

  for (const state of states) {
    if (terminalStates.includes(state)) continue;
    const escape = events
      .map((event) => ({ event, target: table.get(cellKey(state, event)) }))
      .find((cell) => cell.target !== null && cell.target !== undefined && cell.target !== state);

    if (escape === undefined) {
      blocks.push(
        `/-- State ${state} accepts events but no event leaves it: a sink. -/
theorem ${toSnakeCase(state)}_no_escape : ∀ e, escapes .${toPascalCase(state)} e = false := by
  intro e; cases e <;> rfl`,
      );
      continue;
    }
    blocks.push(
      `/-- State ${state} can leave, and this event does it. -/
theorem ${toSnakeCase(state)}_can_leave : ∃ e, escapes .${toPascalCase(state)} e = true :=
  ⟨.${toPascalCase(escape.event)}, rfl⟩`,
    );
  }

  return blocks;
}
