// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/_kiwa/items-handler': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/_kiwa/items-handler').default>>>>
    }
    '/api/items': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/items.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+nitro-server@3.21.8_c4d67b42fa5c459345bea5e6fe4584a6/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}