// Generated by /kiwa-nextjs (Issue #493) from a 9-column Layer 1 spec.
//
// | ID       | Observation       | Given                  | FormData                       | Then                                   |
// |----------|-------------------|------------------------|---------------------------------|----------------------------------------|
// | T-NA-001 | 正常系              | (empty)                | email=user@example.com         | env.redirect.url === '/dashboard'      |
// | T-NA-002 | 入力バリデーション         | (empty)                | (empty)                        | error.message === 'email required'     |
// | T-NA-003 | 入力バリデーション         | (empty)                | email=not-an-email             | error.message === 'invalid email'      |
// | T-NA-004 | 状態遷移            | (empty)                | email=user@example.com         | env.cookies.get('session') === 'sid_…' |

import { describe, expect, it } from 'vitest';
import { invokeServerAction, REDIRECT_SYMBOL } from '@kiwa-lab/nextjs';
import type { RedirectSignal } from '@kiwa-lab/nextjs';
import { login, type LoginEnv } from '../src/login-action.js';

function buildEnv(): {
  env: LoginEnv;
  captured: { redirect: string | null; cookies: Map<string, string> };
} {
  const cookies = new Map<string, string>();
  const captured = { redirect: null as string | null, cookies };
  const env: LoginEnv = {
    redirect: (url) => {
      captured.redirect = url;
      const signal: RedirectSignal = {
        [REDIRECT_SYMBOL]: true,
        url,
        type: 'replace',
      };
      throw signal;
    },
    cookies: {
      set: (name, value) => {
        cookies.set(name, value);
      },
    },
  };
  return { env, captured };
}

describe('login server action', () => {
  it('T-NA-001 正常系: redirects to /dashboard with a session cookie set', async () => {
    const { env: loginEnv, captured } = buildEnv();
    const fd = new FormData();
    fd.set('email', 'user@example.com');
    const { error, env } = await invokeServerAction({
      action: async (formData) => login(formData as FormData, loginEnv),
      formData: fd,
    });
    expect(error).toBeUndefined();
    expect(env.redirect?.url).toBe('/dashboard');
    expect(env.redirect?.type).toBe('replace');
    expect(captured.cookies.get('session')).toBe('sid_user@example.com');
  });

  it('T-NA-002 入力バリデーション: empty FormData → email required', async () => {
    const { env: loginEnv, captured } = buildEnv();
    const { error, env } = await invokeServerAction({
      action: async (formData) => login(formData as FormData, loginEnv),
    });
    expect((error as Error).message).toBe('email required');
    expect(env.redirect).toBeNull();
    expect(captured.cookies.size).toBe(0);
  });

  it('T-NA-003 入力バリデーション: non-@-containing email → invalid email', async () => {
    const { env: loginEnv } = buildEnv();
    const fd = new FormData();
    fd.set('email', 'not-an-email');
    const { error } = await invokeServerAction({
      action: async (formData) => login(formData as FormData, loginEnv),
      formData: fd,
    });
    expect((error as Error).message).toBe('invalid email');
  });

  it('T-NA-004 状態遷移: session cookie name is derived from the submitted email', async () => {
    const { env: loginEnv, captured } = buildEnv();
    const fd = new FormData();
    fd.set('email', 'alice@example.com');
    await invokeServerAction({
      action: async (formData) => login(formData as FormData, loginEnv),
      formData: fd,
    });
    expect(captured.cookies.get('session')).toBe('sid_alice@example.com');
  });
});
