// Generated by /kiwa-nextjs --layer nextjs-middleware (Issue #495) from a 9-column Layer 1 spec.
//
// | ID       | Observation         | Given                       | Then                                       |
// |----------|---------------------|-----------------------------|--------------------------------------------|
// | T-MW-001 | auth gate           | (no cookie)                 | env.action.kind=redirect, url=/login        |
// | T-MW-002 | auth gate bypass    | session=sid_42              | env.action.kind=next                       |
// | T-MW-003 | auth gate api skip  | url=/api/health             | env.action.kind=next                       |
// | T-MW-004 | locale rewrite      | locale=ja, url=/products    | env.action.kind=rewrite, url=/ja/products  |
// | T-MW-005 | locale already set  | url=/ja/products            | env.action.kind=next                       |
// | T-MW-006 | header inject       | (any)                       | x-frame-options=DENY, ... 3 headers        |

import { describe, expect, it } from 'vitest';
import { invokeMiddleware } from '@kiwa/nextjs';
import { authGate, localeRewrite, headerInject } from '../src/middleware.js';

describe('authGate', () => {
  it('T-MW-001 unauthenticated request to /dashboard redirects to /login', async () => {
    const { env } = await invokeMiddleware({
      middleware: authGate,
      url: 'https://example.com/dashboard',
    });
    expect(env.action.kind).toBe('redirect');
    expect(env.action.url).toBe('/login');
  });

  it('T-MW-002 authenticated request passes through with next()', async () => {
    const { env } = await invokeMiddleware({
      middleware: authGate,
      url: 'https://example.com/dashboard',
      cookies: { session: 'sid_42' },
    });
    expect(env.action.kind).toBe('next');
  });

  it('T-MW-003 /api/* paths skip auth gate', async () => {
    const { env } = await invokeMiddleware({
      middleware: authGate,
      url: 'https://example.com/api/health',
    });
    expect(env.action.kind).toBe('next');
  });
});

describe('localeRewrite', () => {
  it('T-MW-004 rewrites pathname with the locale cookie prefix', async () => {
    const { env } = await invokeMiddleware({
      middleware: localeRewrite,
      url: 'https://example.com/products',
      cookies: { locale: 'ja' },
    });
    expect(env.action.kind).toBe('rewrite');
    expect(env.action.url).toBe('/ja/products');
  });

  it('T-MW-005 already-localized URL passes through', async () => {
    const { env } = await invokeMiddleware({
      middleware: localeRewrite,
      url: 'https://example.com/ja/products',
      cookies: { locale: 'ja' },
    });
    expect(env.action.kind).toBe('next');
  });
});

describe('headerInject', () => {
  it('T-MW-006 injects 3 security headers on every request', async () => {
    const { env } = await invokeMiddleware({
      middleware: headerInject,
      url: 'https://example.com/',
    });
    expect(env.action.kind).toBe('next');
    expect(env.responseHeaders.get('x-frame-options')).toBe('DENY');
    expect(env.responseHeaders.get('x-content-type-options')).toBe('nosniff');
    expect(env.responseHeaders.get('referrer-policy')).toBe('same-origin');
  });
});
